In [4]:
import numpy as np
import pandas as pd

# Generate a 4x4 table of random integers between 0 and 100
random_table = np.random.randint(0, 101, size=(4, 4))
print(random_table)

# Assign the table to a DataFrame
df = pd.DataFrame(random_table, columns=['A', 'B', 'C', 'D'])
print(df)

[[98 91 53 19]
 [54  0 15 87]
 [ 1 83 77 41]
 [84 87 64 24]]
    A   B   C   D
0  98  91  53  19
1  54   0  15  87
2   1  83  77  41
3  84  87  64  24


In [5]:
import random

# List of four-letter words
four_letter_words = ["tree", "book", "fish", "lamp", "door", "cake", "milk", "ball", "star", "moon", "wind", "fire", "snow", "rain", "sand", "rock", "leaf", "frog", "wolf", "bear"]

# Generate a 6x6 table with random four-letter words
random_word_table = np.array([[random.choice(four_letter_words) for _ in range(6)] for _ in range(6)])
print(random_word_table)

df_words = pd.DataFrame(random_word_table, columns=['A', 'B', 'C', 'D', 'E', 'F'])
print(df_words)

[['book' 'moon' 'snow' 'cake' 'door' 'fish']
 ['star' 'moon' 'door' 'book' 'frog' 'wolf']
 ['rock' 'milk' 'lamp' 'moon' 'star' 'fish']
 ['lamp' 'sand' 'book' 'cake' 'door' 'tree']
 ['bear' 'tree' 'moon' 'star' 'wind' 'door']
 ['wind' 'moon' 'leaf' 'bear' 'snow' 'tree']]
      A     B     C     D     E     F
0  book  moon  snow  cake  door  fish
1  star  moon  door  book  frog  wolf
2  rock  milk  lamp  moon  star  fish
3  lamp  sand  book  cake  door  tree
4  bear  tree  moon  star  wind  door
5  wind  moon  leaf  bear  snow  tree


In [ ]:
df.to_csv('output.csv', index=False)
df_words.to_csv('output_words.csv', index=False)