In [2]:
import numpy as np
import pandas as pd

# Generate a 4x4 table of random integers between 0 and 100
random_table = np.random.randint(0, 101, size=(4, 4))
print(random_table)

# Assign the table to a DataFrame
df = pd.DataFrame(random_table, columns=['A', 'B', 'C', 'D'])
print(df)

[[ 70   8 100  98]
 [ 80  26  28  65]
 [ 94  16  31  71]
 [ 75  11  26  60]]
    A   B    C   D
0  70   8  100  98
1  80  26   28  65
2  94  16   31  71
3  75  11   26  60


In [4]:
import random

# List of four-letter words
four_letter_words = ["tree", "book", "fish", "lamp", "door", "cake", "milk", "ball", "star", "moon", "wind", "fire", "snow", "rain", "sand", "rock", "leaf", "frog", "wolf", "bear"]

# Generate a 6x6 table with random four-letter words
random_word_table = np.array([[random.choice(four_letter_words) for _ in range(6)] for _ in range(6)])
print(random_word_table)

df_words = pd.DataFrame(random_word_table, columns=['A', 'B', 'C', 'D', 'E', 'F'])
print(df_words)

[['wind' 'tree' 'book' 'bear' 'star' 'ball']
 ['fire' 'rock' 'rain' 'rock' 'sand' 'fish']
 ['rock' 'moon' 'fire' 'moon' 'fish' 'frog']
 ['bear' 'star' 'star' 'tree' 'fish' 'door']
 ['star' 'tree' 'fire' 'rain' 'leaf' 'star']
 ['bear' 'moon' 'fire' 'rain' 'frog' 'book']]
      A     B     C     D     E     F
0  wind  tree  book  bear  star  ball
1  fire  rock  rain  rock  sand  fish
2  rock  moon  fire  moon  fish  frog
3  bear  star  star  tree  fish  door
4  star  tree  fire  rain  leaf  star
5  bear  moon  fire  rain  frog  book


In [ ]:
df.to_csv('output.csv', index=False)
df_words.to_csv('output_words.csv', index=False)